name: rustfmt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install stable
      run: |
        rustup toolchain add nightly --component rustfmt
        rustup update
    - name: Build
      run: cargo +nightly fmt -- --check
    
